import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import Section from '../components/Section'
import Supper from '../components/Supper'
import Mobile from '../components/Mobile'
import Safety from '../components/Safety'
import Video from '../components/Video'
import { Cards, Career } from '../components'
import About from '../components/About'
import Experience from '../components/Experience'
import Footer from '../components/Footer'

const  Card = [
  {id:1, image:"https://bykea.com/wp-content/uploads/2020/02/Updated-1.jpg",
title:"Safety",
 desc:"All of our partners hold a valid driver's license, are tracked and undergo a thorough background check to guarantee your safety. trip insured as apessanger and as a shipper",
 button:"Read more"},
{id:2, image:"https://bykea.com/wp-content/uploads/2020/02/Updated-2.jpg",
title:"Accessibility", desc:"All of our partners hold a valid driver's license, are tracked and undergo a thorough background check to guarantee safety. trip insured as apessanger and as a shipper", button:"Read More"}
]
const  Carditems = [
  {id:1, title:"Career at Bykeya", image:"https://bykea.com/wp-content/uploads/elementor/thumbs/1-min-scaled-phn7qimpxx17bv9qkyvusmvvbfdsm3krowyh3ohrc0.jpg", desc:"we have a best driver you can book our shappy you booked our our rider",
 button:"Read more"},
{id:2, image:"https://bykea.com/wp-content/uploads/2020/03/Partners-updated.jpg",
title:"Partner with Bykeya", desc:" undergo a thorough nsured as apessanger and as a shipper", button:"Read More"}
]

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bykeya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Header/>
<div className='bg-gray-100'>
<Section/>
    <Supper/>
    <Mobile/>
    <Safety/>
    <Video/>
    <div className=' grid grid-cols-1  grid-rows-2 xl:flex space-x-4 pl-20'>
    {Card?.map((item)=>(
                 <Cards {...item}/>
                   ) )}
   
    </div>
    <About/>
    <div className='grid grid-cols-1  grid-rows-2 xl:flex  space-x-4 pl-20 mt-28'>
    {Carditems?.map((item)=>(
                 <Career {...item}/>
                   ) )}
   
    </div>
    <Experience/>
    <Footer/>
</div>
    </div>
  )
}
